M48
; DRILL file {KiCad 7.0.1} date Thu Apr 20 13:05:56 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-20T13:05:56-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.9387Y-4.425
X3.9387Y-4.5983
T2
X3.937Y-5.3296
X3.9373Y-2.6718
X7.2732Y-5.3298
X7.2756Y-2.7008
T0
M30
